Vagrant.configure('2') do |config|
  config.ssh.insert_key = false
  config.vm.synced_folder '../.',
                          '/vagrant',
                          mount_options: ['dmode=775,fmode=755']
  config.vm.box = 'bento/centos-7.8'

  config.vm.provider 'virtualbox' do |v|
    v.memory = 2048
  end
end
