Vagrant.configure('2') do |config|
  config.ssh.insert_key = false

  config.vm.synced_folder '../.',
                          '/vagrant',
                          mount_options: ['dmode=775,fmode=755']
  config.vm.box = 'bento/centos-7.8'

  config.vm.provision 'ansible_local' do |ansible|
    ansible.install_mode = "pip3"
    ansible.galaxy_role_file = "/vagrant/part02/requirements.yml"
    ansible.playbook = "/vagrant/part02/provision_me.yml"
    ansible.version = "2.9.23"
    ansible.verbose = 'v'
  end

  config.vm.provider 'virtualbox' do |v|
    v.memory = 2048
  end
end
