## to run vagrant box on Mac with M1 :  
## install brew ##
# /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
# echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> /Users/A345618/.zprofile
# eval "$(/opt/homebrew/bin/brew shellenv)"
##
## install vagrant
# brew install vagrant
##
## install qemu
# brew install qemu
##
## install vagrant plugin https://github.com/ppggff/vagrant-qemu
# vagrant plugin install vagrant-qemu
##

Vagrant.configure('2') do |config|
  config.vm.provider "qemu" do |qe|
    qe.arch = "x86_64"
    qe.machine = "q35"
    qe.cpu = "max"
    qe.net_device = "virtio-net-pci"
    qe.memory = "4G"
  end
  
  config.vm.box = 'centos/7'
  
  config.vm.synced_folder '../', '/vagrant', mount_options: ['dmode=775,fmode=755']
  
  config.vm.provision 'ansible_local' do |ansible|
    # https://www.vagrantup.com/docs/provisioning/ansible_local
    # https://www.vagrantup.com/docs/provisioning/ansible_common
    ansible.install = true
    ansible.galaxy_roles_path = "/home/vagrant/.ansible/roles"
    ansible.galaxy_role_file = "/vagrant/vagrant/requirements.yml"
    ansible.playbook = "/vagrant/vagrant/provision_me.yml"
    ansible.verbose = 'v'
  end
end
